### ISSUE TITLE
最近版本体积暴增疑问

### ISSUE THREAD

**Issue by ss916** [alecthw/mmdb_china_ip_list#10]
20210726版本大小为4 MB
20210802版的体积大小突然暴增为15.3 MB
这是里面ip数据重复了吗？

**Comment by alecthw** [comment]
我瞧瞧为啥，代码没动过

**Comment by alecthw** [comment]
体积暴增也不应是重复ip导致的，这玩意儿最终会收敛成树

**Comment by alecthw** [comment]
官方的版本也接近8M了，不清楚mmdb最近干了啥

**Comment by alecthw** [comment]
重编之后是7.3M了，和官方大小基本一致了，估计官方最近修改了啥吧

**Comment by alecthw** [comment]
这两天看了下，mmdb应该是把ip分的更细了，导致文件大小涨到了7M多。
看了clash的源码，只用到了 record.Country.IsoCode，正在制作一个只含 iso_code和geoname_id的版本，去除其他无用的额外信息，目前构建出的大小在2M内，预计本周末上传。
后续计划提供完全和轻量两个版本

**Comment by ss916** [comment]
大佬牛逼！
对体积敏感主要是在一些嵌入式设备上使用，文件大小一般控制在4MB以内就没问题。

**Comment by alecthw** [comment]
release分支已上传lite，可以下载了试试有没有问题

**Comment by ss916** [comment]
使用了几天Country.mmdb lite版本，未发现什么问题。再次感谢开发者！
