### ISSUE TITLE
lite版里面没有收录中国ipv6 IP吗

### ISSUE THREAD

**Issue by testiknn** [alecthw/mmdb_china_ip_list#11]
比如
中国联通2408.xxxx
中国电信240e.xxxx
中国移动2409.xxxx
以上这些经过测试在lite版里并没分类到cn IP

测试用完整版就有分类到cn ip里

**Comment by alecthw** [comment]
lite只插入了[china_ip_list](https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt)和[纯真CN数据库](https://raw.githubusercontent.com/metowolf/iplist/master/data/country/CN.txt)的数据，没有ipv6。
有没有cn6的来源，有的话可以加进去……

**Comment by alecthw** [comment]
我先试试加上ipv6，看看大小增加多少吧。ipv6目前确实需要的人比较少

**Comment by alecthw** [comment]
已补充ipv6数据。。。。。。。

**Comment by testiknn** [comment]
多谢，已测试正常归类中国ipv6 IP了

**Comment by testiknn** [comment]
ipv6数据建议直接使用 ftp.apnic.net 的数据源：
https://ftp.apnic.net/stats/apnic/delegated-apnic-latest

生成ipv6：
``cat delegated-apnic-latest | awk -F '|' '/CN/&&/ipv6/ {print $4 "/" $5}' | sort  > cn_ipv6.txt``

同理，可以生成cn ipv4数据：
``cat delegated-apnic-latest | awk -F '|' '/CN/&&/ipv4/ {print $4 "/" 32-log($5)/log(2)}' | sort -n > cn_ipv4.txt``


~~测试发现Clang.CN网站使用的数据也是来自ftp.apnic.net，但并没有看到注明出处。~~
我们直接用上游数据就行了。
