### ISSUE TITLE
Surge 使用 lite 版是正常的，但是无法解析使用非精简版的。

### ISSUE THREAD

**Issue by 4au** [alecthw/mmdb_china_ip_list#12]
RT.

**Comment by alecthw** [comment]
备注上来
![image](https://user-images.githubusercontent.com/22856212/148177940-c3cff519-cdff-4292-8f6a-de31

**Comment by alecthw** [comment]
![image](https://user-images.githubusercontent.com/22856212/148180820-58d407bf-43a5-4340-85a5-a1c625644574.png)
感觉没问题啊……
languages里都是string

**Comment by 4au** [comment]
> 
Surge 提示无效数据。其它工具没用过，不清楚。
二进制文件直接叠加可能会有问题，建议通过CSV格式文件生成完整版 `mmdb`.

**Comment by alecthw** [comment]
确实从零构建就是正常的，也不清楚为啥……
![image](https://user-images.githubusercontent.com/22856212/225891560-3aa8b4ac-04bc-4350-a3ef-77d338d846d8.png)
