### ISSUE TITLE
完整版能否先去除官方版CN的数据再进行叠加

### ISSUE THREAD

**Issue by returnL** [alecthw/mmdb_china_ip_list#13]
如果一个IP在原版中被误判为CN，而且又恰好无法被后来添加的数据所覆盖，那么依旧会被误判。
平时遇到的误判大多都是国外IP被误判为CN，如果不事先删除原版的CN数据，直接进行叠加，这些被误判断国外IP显然无法被覆盖，也就没有解决此类误判

**Comment by alecthw** [comment]
> 如果一个IP在原版中被误判为CN，而且又恰好无法被后来添加的数据所覆盖，那么依旧会被误判。 平时遇到的误判大多都是国外IP被误判为CN，如果不事先删除原版的CN数据，直接进行叠加，这些被误判断国外IP显然无法被覆盖，也就没有解决此类误判

等放假我看看，年底比较忙

**Comment by returnL** [comment]
好的，麻烦您了

**Comment by alecthw** [comment]
> 好的，麻烦您了

没有找到删除接口……
我在lite版本里处理了下，读取官方数据的时候把cn的数据跳过了，如果只需识别国家，lite版本足够用了

``` go
......
if geoNameId == 1814991 {
	continue
}
......
```

**Comment by returnL** [comment]
> > 好的，麻烦您了
> 
> 没有找到删除接口…… 我在lite版本里处理了下，读取官方数据的时候把cn的数据跳过了，如果只需识别国家，lite版本足够用了
> 
> ```go
> ......
> if geoNameId == 1814991 {
> 	continue
> }
> ......
> ```

好的，感谢

**Comment by alecthw** [comment]
> > > 好的，麻烦您了
> > 
> > 
> > 没有找到删除接口…… 我在lite版本里处理了下，读取官方数据的时候把cn的数据跳过了，如果只需识别国家，lite版本足够用了
> > ```go
> > ......
> > if geoNameId == 1814991 {
> > 	continue
> > }
> > ......
> > ```
> 
> 好的，感谢

lite版本也是包含了全国家的，只是仅写了iso_code 和 geoname_id来缩小体积，大部分情况也只需要这两个数据
