### ISSUE TITLE
是否能生成一个City版本的mmdb库

### ISSUE THREAD

**Issue by ShunqinChen** [alecthw/mmdb_china_ip_list#14]
只有Country的话只能限定到国家,基于国内省份或城市的需求就无法实现了, GeoLite2-City库也有类似不精确的问题

**Comment by alecthw** [comment]
> 只有Country的话只能限定到国家,基于国内省份或城市的需求就无法实现了, GeoLite2-City库也有类似不精确的问题

做这个的本质目的就是为了科学上网而已啊……
商业用的话，还是建议用ipip的数据库吧

**Comment by ShunqinChen** [comment]
嗯,感谢回复,  后来使用了IPIP的库了
