### ISSUE TITLE
能否提供一个只有cn数据的Lite版本

### ISSUE THREAD

**Issue by fiiir** [alecthw/mmdb_china_ip_list#15]
Lite版本真香，有一个想法，希望大佬能考虑一下：
各类接管流量分流的app和软件，配置文件上对于mmdb的应用，几乎都是清一色的geoip,cn和非cn，这种使用场景下cn以外的数据显然没有存在的必要

能否提供一个只有cn数据的Lite版本，只包含china_ip_list、纯真CN和Clang.CN，并且仅写入了 iso_code 和 geoname_id
这样可以将检索效率提高到极致，对移动设备的续航也可以起到不错的作用

**Comment by alecthw** [comment]
> Lite版本真香，有一个想法，希望大佬能考虑一下： 各类接管流量分流的app和软件，配置文件上对于mmdb的应用，几乎都是清一色的geoip,cn和非cn，这种使用场景下cn以外的数据显然没有存在的必要
> 
> 能否提供一个只有cn数据的Lite版本，只包含china_ip_list、纯真CN和Clang.CN，并且仅写入了 iso_code 和 geoname_id 这样可以将检索效率提高到极致，对移动设备的续航也可以起到不错的作用

没必要啊，其实快不了多少的……

**Comment by fiiir** [comment]
> > Lite版本真香，有一个想法，希望大佬能考虑一下： 各类接管流量分流的app和软件，配置文件上对于mmdb的应用，几乎都是清一色的geoip,cn和非cn，这种使用场景下cn以外的数据显然没有存在的必要
> > 
> > 能否提供一个只有cn数据的Lite版本，只包含china_ip_list、纯真CN和Clang.CN，并且仅写入了 iso_code 和 geoname_id 这样可以将检索效率提高到极致，对移动设备的续航也可以起到不错的作用
> 
> 没必要啊，其实快不了多少的……

苍蝇再小……也是肉

**Comment by alecthw** [comment]
> > > Lite版本真香，有一个想法，希望大佬能考虑一下： 各类接管流量分流的app和软件，配置文件上对于mmdb的应用，几乎都是清一色的geoip,cn和非cn，这种使用场景下cn以外的数据显然没有存在的必要
> > > 能否提供一个只有cn数据的Lite版本，只包含china_ip_list、纯真CN和Clang.CN，并且仅写入了 iso_code 和 geoname_id 这样可以将检索效率提高到极致，对移动设备的续航也可以起到不错的作用
> > 
> > 
> > 没必要啊，其实快不了多少的……
> 
> 苍蝇再小……也是肉

实在需要的话，可以fork一份，然后注释这行代码，自己构建
```go
func buildLite() {
        ......
	insertCsvSkipCN("GeoLite2-Country-Blocks-IPv4.csv")
        ......
}
```
