### ISSUE TITLE
好人做到底啊。

### ISSUE THREAD

**Issue by ghost** [alecthw/mmdb_china_ip_list#18]
能做个这样的版本吗？

geoip,telegram,proxy  
geoip,lan,direct
geoip,cn,direct

不用 IP-CIDR 规则是希望可以在日志中很方便的看到是什么流量。
不用 rule-set 是因为域名全部用 geosite 实现了，不想因为一个 telegram 再下载规则（因为不知道什么时候就下载不了了）
如果软件不支持自定义的写法，并且开发商不想支持，甚至可以用国家代码代替（比如 us hk 代替 telegram lan ）。

希望使用的数据来源：
https://github.com/misakaio/chnroutes2
https://core.telegram.org/resources/cidr.txt

**Comment by ghost** [comment]
查了一下，有 tg la 两个国家代码，刚好替换 telegram lan.

**Comment by alecthw** [comment]
> 查了一下，有 tg la 两个国家代码，刚好替换 telegram lan.

这样不好的，会导致本身的国家ip变成这个，从而丢失某些国家的匹配。
回头我来坐个仅包含中国，国外的ip不写，写一些Netflix和telegram等服务的进去

**Comment by MaurUppi** [comment]
> > 查了一下，有 tg la 两个国家代码，刚好替换 telegram lan.
> 
> 这样不好的，会导致本身的国家ip变成这个，从而丢失某些国家的匹配。 回头我来坐个仅包含中国，国外的ip不写，写一些Netflix和telegram等服务的进去

贴出如下的repo并非对Alecthw不敬，我也是在用你的Courtry.mmdb

https://github.com/Loyalsoldier/geoip
- 新增类别（方便有特殊需求的用户使用）：
  - geoip:cloudflare（GEOIP,CLOUDFLARE）
  - geoip:cloudfront（GEOIP,CLOUDFRONT）
  - geoip:facebook（GEOIP,FACEBOOK）
  -  geoip:fastly（GEOIP,FASTLY）
  -  geoip:google（GEOIP,GOOGLE）
  -  geoip:netflix（GEOIP,NETFLIX）
  - geoip:telegram（GEOIP,TELEGRAM）
  - geoip:twitter（GEOIP,TWITTER）

这个repo的实现的方式，应该是如下两端配置
- https://github.com/Loyalsoldier/geoip/blob/bf51d6afac442fec800bb15f2d7545a1e3bba262/.github/workflows/build.yml#L41-L46
- https://github.com/Loyalsoldier/geoip/blob/bf51d6afac442fec800bb15f2d7545a1e3bba262/config.json#L48-L75

**Comment by alecthw** [comment]
> > > 查了一下，有 tg la 两个国家代码，刚好替换 telegram lan.
> > 
> > 
> > 这样不好的，会导致本身的国家ip变成这个，从而丢失某些国家的匹配。 回头我来坐个仅包含中国，国外的ip不写，写一些Netflix和telegram等服务的进去
> 
> 贴出如下的repo并非对Alecthw不敬，我也是在用你的Courtry.mmdb
> 
> https://github.com/Loyalsoldier/geoip
> 
> * 新增类别（方便有特殊需求的用户使用）：
>   
>   * geoip:cloudflare（GEOIP,CLOUDFLARE）
>   * geoip:cloudfront（GEOIP,CLOUDFRONT）
>   * geoip:facebook（GEOIP,FACEBOOK）
>   * geoip:fastly（GEOIP,FASTLY）
>   * geoip:google（GEOIP,GOOGLE）
>   * geoip:netflix（GEOIP,NETFLIX）
>   * geoip:telegram（GEOIP,TELEGRAM）
>   * geoip:twitter（GEOIP,TWITTER）
> 
> 这个repo的实现的方式，应该是如下两端配置
> 
> * https://github.com/Loyalsoldier/geoip/blob/bf51d6afac442fec800bb15f2d7545a1e3bba262/.github/workflows/build.yml#L41-L46
> * https://github.com/Loyalsoldier/geoip/blob/bf51d6afac442fec800bb15f2d7545a1e3bba262/config.json#L48-L75

这没啥，个人选择罢了。当初做这个时候，meta还没稳定。
clash meta支持使用这个，可以参考 https://wiki.metacubex.one/config/general/#geo
