### ISSUE TITLE
"is_in_european_union"字段如何使用

### ISSUE THREAD

**Issue by kiligone** [alecthw/mmdb_china_ip_list#19]
"is_in_european_union"字段是否可以判断ip属于欧洲的ip，如果要写到openclash的规则中要怎么使用？

**Comment by alecthw** [comment]
> "is_in_european_union"字段是否可以判断ip属于欧洲的ip，如果要写到openclash的规则中要怎么使用？

只能判断是不是欧盟，不能完全代表欧洲。openclash没识别这个属性，要用得改源码
