### ISSUE TITLE
感觉CSV源可以加上db-ip？

### ISSUE THREAD

**Issue by nasbdh9** [alecthw/mmdb_china_ip_list#2]
不用key就能获取，每月更新，且使用CC4.0协议分发
例：
https://download.db-ip.com/free/dbip-country-lite-2020-05.csv.gz
https://download.db-ip.com/free/dbip-country-lite-2020-05.mmdb.gz

再加上CI的话基本就数据源有更新就可以自动release

而且哪怕是中国以外的IP记录比MaxMind的要详细的样子？（虽然个人觉得还是差不多

**Comment by alecthw** [comment]
正常情况下前面都是流媒体和应用的匹配，到geoip判断cn直连，剩下的走代理，只要cn的库补全就可以了吧，所以基础的用哪个都差不多。
搞这个的起因是从passwall换到openclash后，配成白名单模式，王者荣耀和腾讯视频的部分视频走进了代理，尝试了几个大神的规则没能解决，后来自己把china_ip_list作为CIDR加进去后，一切都正常了，就是规则巨长，clash加载慢，看着也难受，然后自己动手琢磨生成mmdb替换了官方的。

**Comment by nasbdh9** [comment]
有空我整一下...
clash做策略我觉得还是不太灵活（在调用上）现在ipset用着先了
