### ISSUE TITLE
a老师，请问用于openclash集合的名称代码叫什么。。。

### ISSUE THREAD

**Issue by wzy105** [alecthw/mmdb_china_ip_list#21]
例如：geoip：CN 是国内ip，那非国内ip的名称是什么？

**Comment by alecthw** [comment]
非的话判断时候取反。
其他国家码参考：https://zh.m.wikipedia.org/wiki/ISO_3166-1

**Comment by wzy105** [comment]
> 非的话判断时候取反。 其他国家码参考：https://zh.m.wikipedia.org/wiki/ISO_3166-1

明白了感谢a老湿
