### ISSUE TITLE
IP CIDR 融合问题

### ISSUE THREAD

**Issue by MaurUppi** [alecthw/mmdb_china_ip_list#22]
@alecthw 请教一下

根据你的描述
> 
> 由于构建mmdb，后者覆盖前者的特性，ip列表的插入顺序如下：
> 
> 1. [Clang.CN](https://ispip.clang.cn/)
> 2. [纯真CN数据库](https://raw.githubusercontent.com/metowolf/iplist/master/data/country/CN.txt) `国内大陆 IP 段`
> 3. [china_ip_list](https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt)
> 
> 

`后者覆盖前者的特性` 是否指的是 往mmdb插入数据的时候，利用数据库不可插入重复数据的特性，完成上述CIDR数据的`融合`呢？
即，没有使用例如GO语言现成的库（或者你手写了），首先处理完TXT文本CIDR的处理，才往MMDB导入？

**Comment by alecthw** [comment]
> @alecthw 请教一下
> 
> 根据你的描述
> 
> > 由于构建mmdb，后者覆盖前者的特性，ip列表的插入顺序如下：
> > 
> > 1. [Clang.CN](https://ispip.clang.cn/)
> > 2. [纯真CN数据库](https://raw.githubusercontent.com/metowolf/iplist/master/data/country/CN.txt) `国内大陆 IP 段`
> > 3. [china_ip_list](https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt)
> 
> `后者覆盖前者的特性` 是否指的是 往mmdb插入数据的时候，利用数据库不可插入重复数据的特性，完成上述CIDR数据的`融合`呢？ 即，没有使用例如GO语言现成的库（或者你手写了），首先处理完TXT文本CIDR的处理，才往MMDB导入？

没有预处理，直接插入的。数据不可重复，后插入的会覆盖前者。

**Comment by MaurUppi** [comment]
> > @alecthw 请教一下
> > 根据你的描述
> > > 由于构建mmdb，后者覆盖前者的特性，ip列表的插入顺序如下：
> > > 
> > > 1. [Clang.CN](https://ispip.clang.cn/)
> > > 2. [纯真CN数据库](https://raw.githubusercontent.com/metowolf/iplist/master/data/country/CN.txt) `国内大陆 IP 段`
> > > 3. [china_ip_list](https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt)
> > 
> > 
> > `后者覆盖前者的特性` 是否指的是 往mmdb插入数据的时候，利用数据库不可插入重复数据的特性，完成上述CIDR数据的`融合`呢？ 即，没有使用例如GO语言现成的库（或者你手写了），首先处理完TXT文本CIDR的处理，才往MMDB导入？
> 
> 没有预处理，直接插入的。数据不可重复，后插入的会覆盖前者。

感谢答复。

如果是`数据不可重复，后插入的会覆盖前者`的逻辑，相当于就是利用数据库本身的规则，但就是得特别注意**插入文件顺序**的原因了。

我还想着是不是先用类似如下的工具会更好点呢：
[ip_compact](https://github.com/x-way/ip_compact)
"Compact" a list of IP prefixes (removing duplicates, merging adjacent ranges).

**Comment by alecthw** [comment]
> > > @alecthw 请教一下
> > > 根据你的描述
> > > > 由于构建mmdb，后者覆盖前者的特性，ip列表的插入顺序如下：
> > > > 
> > > > 1. [Clang.CN](https://ispip.clang.cn/)
> > > > 2. [纯真CN数据库](https://raw.githubusercontent.com/metowolf/iplist/master/data/country/CN.txt) `国内大陆 IP 段`
> > > > 3. [china_ip_list](https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt)
> > > 
> > > 
> > > `后者覆盖前者的特性` 是否指的是 往mmdb插入数据的时候，利用数据库不可插入重复数据的特性，完成上述CIDR数据的`融合`呢？ 即，没有使用例如GO语言现成的库（或者你手写了），首先处理完TXT文本CIDR的处理，才往MMDB导入？
> > 
> > 
> > 没有预处理，直接插入的。数据不可重复，后插入的会覆盖前者。
> 
> 感谢答复。
> 
> 如果是`数据不可重复，后插入的会覆盖前者`的逻辑，相当于就是利用数据库本身的规则，但就是得特别注意**插入文件顺序**的原因了。
> 
> 我还想着是不是先用类似如下的工具会更好点呢： [ip_compact](https://github.com/x-way/ip_compact) "Compact" a list of IP prefixes (removing duplicates, merging adjacent ranges).

没必要，结果是一样的，数据库本身是个树匹配
