### ISSUE TITLE
能否实现跟nali工具结合然后可以自定义修改运营商名称？

### ISSUE THREAD

**Issue by maojianyou** [alecthw/mmdb_china_ip_list#24]
因为有些自定义设置的IP地址段是不准的，比如我临时用30.30.1.1实际上这是互联地址，或者我重新到互联网申请一段地址段，也是没有归属的，比如标识是亚太，我能否自定义修改这个库，或者新增一个provate.mmdb库，优先识别

**Comment by alecthw** [comment]
> 因为有些自定义设置的IP地址段是不准的，比如我临时用30.30.1.1实际上这是互联地址，或者我重新到互联网申请一段地址段，也是没有归属的，比如标识是亚太，我能否自定义修改这个库，或者新增一个provate.mmdb库，优先识别

可以的，覆盖或者生成一个新的都行

**Comment by maojianyou** [comment]
> > 因为有些自定义设置的IP地址段是不准的，比如我临时用30.30.1.1实际上这是互联地址，或者我重新到互联网申请一段地址段，也是没有归属的，比如标识是亚太，我能否自定义修改这个库，或者新增一个provate.mmdb库，优先识别
> 
> 可以的，覆盖或者生成一个新的都行

具体怎么用你这个，感觉没有详细教程，无法知道使用，因不是研发
![image](https://github.com/alecthw/mmdb_china_ip_list/assets/55315920/a85df119-5904-43db-bbb8-e2226f3633f9)
比如这个是毛里求斯，默认nali是调用qqwry.dat 这个纯真库，但其实这个地址假设就是我自己的地址，不是毛里求斯，我如何自定义修改这个区域及运营商

**Comment by alecthw** [comment]
> > > 因为有些自定义设置的IP地址段是不准的，比如我临时用30.30.1.1实际上这是互联地址，或者我重新到互联网申请一段地址段，也是没有归属的，比如标识是亚太，我能否自定义修改这个库，或者新增一个provate.mmdb库，优先识别
> > 
> > 
> > 可以的，覆盖或者生成一个新的都行
> 
> 具体怎么用你这个，感觉没有详细教程，无法知道使用，因不是研发 ![image](https://private-user-images.githubusercontent.com/55315920/331792405-a85df119-5904-43db-bbb8-e2226f3633f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTMxMjIsIm5iZiI6MTcxNjExMjgyMiwicGF0aCI6Ii81NTMxNTkyMC8zMzE3OTI0MDUtYTg1ZGYxMTktNTkwNC00M2RiLWJiYjgtZTIyMjZmMzYzM2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEwMDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTNhMWMxYjlhYWYxOTgyMmI1YjIyYjU3NDg0MWRjOTIwNjdiZDYxYWM3ZjBkY2JhYzExOGMwODZkYmUwMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sFziGYMFrTPxL7Plc_kLxg5NnBVlMmxhSnorRpkuKHM) 比如这个是毛里求斯，默认nali是调用qqwry.dat 这个纯真库，但其实这个地址假设就是我自己的地址，不是毛里求斯，我如何自定义修改这个区域及运营商

可以参考代码。
官方教程参考：https://github.com/maxmind/mmdbwriter
需要代做的话可以tg联系

**Comment by maojianyou** [comment]
> > > > 因为有些自定义设置的IP地址段是不准的，比如我临时用30.30.1.1实际上这是互联地址，或者我重新到互联网申请一段地址段，也是没有归属的，比如标识是亚太，我能否自定义修改这个库，或者新增一个provate.mmdb库，优先识别
> > > 
> > > 
> > > 可以的，覆盖或者生成一个新的都行
> > 
> > 
> > 具体怎么用你这个，感觉没有详细教程，无法知道使用，因不是研发 ![image](https://private-user-images.githubusercontent.com/55315920/331792405-a85df119-5904-43db-bbb8-e2226f3633f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTMxMjIsIm5iZiI6MTcxNjExMjgyMiwicGF0aCI6Ii81NTMxNTkyMC8zMzE3OTI0MDUtYTg1ZGYxMTktNTkwNC00M2RiLWJiYjgtZTIyMjZmMzYzM2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEwMDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTNhMWMxYjlhYWYxOTgyMmI1YjIyYjU3NDg0MWRjOTIwNjdiZDYxYWM3ZjBkY2JhYzExOGMwODZkYmUwMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sFziGYMFrTPxL7Plc_kLxg5NnBVlMmxhSnorRpkuKHM) 比如这个是毛里求斯，默认nali是调用qqwry.dat 这个纯真库，但其实这个地址假设就是我自己的地址，不是毛里求斯，我如何自定义修改这个区域及运营商
> 
> 可以参考代码。 官方教程参考：https://github.com/maxmind/mmdbwriter 需要代做的话可以tg联系

有没有教程，貌似执行错误
![image](https://github.com/alecthw/mmdb_china_ip_list/assets/55315920/49e0dcd6-d0f1-4d3a-b2f7-e9c292c53a65)

**Comment by maojianyou** [comment]
> > 因为有些自定义设置的IP地址段是不准的，比如我临时用30.30.1.1实际上这是互联地址，或者我重新到互联网申请一段地址段，也是没有归属的，比如标识是亚太，我能否自定义修改这个库，或者新增一个provate.mmdb库，优先识别
> 
> 可以的，覆盖或者生成一个新的都行

![image](https://github.com/alecthw/mmdb_china_ip_list/assets/55315920/d18c5b5c-0dd5-49fd-9a73-002fca321fe1)
执行编译报错，纯属个人爱好

**Comment by alecthw** [comment]
> > > 因为有些自定义设置的IP地址段是不准的，比如我临时用30.30.1.1实际上这是互联地址，或者我重新到互联网申请一段地址段，也是没有归属的，比如标识是亚太，我能否自定义修改这个库，或者新增一个provate.mmdb库，优先识别
> > 
> > 
> > 可以的，覆盖或者生成一个新的都行
> 
> ![image](https://private-user-images.githubusercontent.com/55315920/333835678-d18c5b5c-0dd5-49fd-9a73-002fca321fe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2ODM1ODIsIm5iZiI6MTcxNjY4MzI4MiwicGF0aCI6Ii81NTMxNTkyMC8zMzM4MzU2NzgtZDE4YzViNWMtMGRkNS00OWZkLTlhNzMtMDAyZmNhMzIxZmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDAwMjgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYjBjY2JiODkxMDNiYjAxMjUyODI4ZDlmNDM2ZmQxZDFmMDEwMDIwYWY5OTA2NWJjNzE2MjM4NTQxNDI1ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9TNUZHseplO6HG1VAG2jq-MtCrAnum0_-Q4ilSl9lX0) 执行编译报错，纯属个人爱好

用go版本的，别用perl版本的
