### ISSUE TITLE
请问往后的releases，能否多加一个只有（chinaip+纯真ip）版本

### ISSUE THREAD

**Issue by ghost** [alecthw/mmdb_china_ip_list#7]
如果maxmind的ip不准，可能会出现把有些ip误判为国内的ip，并且绝大多数用户大概只需要使用到cn的ip，所以我觉得只需要chinaip+纯真ip的版本可能效果会更好。由于对linux不熟，所以不会自己弄。就厚着脸皮来麻烦大佬了。感谢大佬做出这个项目。

**Comment by alecthw** [comment]
> 如果maxmind的ip不准，可能会出现把有些ip误判为国内的ip，并且绝大多数用户大概只需要使用到cn的ip，所以我觉得只需要chinaip+纯真ip的版本可能效果会更好。由于对linux不熟，所以不会自己弄。就厚着脸皮来麻烦大佬了。感谢大佬做出这个项目。

理论上，构建的时候，是先插入的mmdb的数据，后插入的chinaip和纯真的数据，后者会覆盖前者，国内ip的匹配应该是准确的。如果确实有问题，可以尝试下这个兄弟的[ipip2mmdb](https://github.com/JMVoid/ipip2mmdb)，只有chinaip的数据

**Comment by ghost** [comment]
因为大佬更新的比较勤一点，哈哈哈
