### ISSUE TITLE
可否往文件内加入专属的 Telegram 列表？

### ISSUE THREAD

**Issue by Loyalsoldier** [alecthw/mmdb_china_ip_list#8]
类似 https://github.com/Loyalsoldier/v2ray-rules-dat#geoipdat

**Comment by alecthw** [comment]
我也这么想过，理论上可以，但是mmdb实现上，最后插入tg的ip段，应该会覆盖其本来所在的国家段。等我忙完这段时间试下，不行的话可以新增一个独立的文件，来收录app的ip，然后找客户端的开发协商下支持自定义文件。

**Comment by alecthw** [comment]
> 类似 https://github.com/Loyalsoldier/v2ray-rules-dat#geoipdat

不过这个必要性好像不大，正常chinaip或者非chinaip都是在最后匹配，为了加快速度使用mmdb的。对于app应用，由于ip段很少，放到里面起到的作用不明显
