### ISSUE TITLE
建议手工添加阿里云部分网段

### ISSUE THREAD

**Issue by Nautilus-Erkkinen** [alecthw/mmdb_china_ip_list#9]
目前部分阿里云的IP段并没有被列表收录（如8.134.0.0这一段），导致部分网络连接出现非正常绕道情况。请考虑手工添加。
数据来源：https://whois.ipip.net/AS37963
===========================================
8.129.0.0/17
8.129.0.0/16
8.129.128.0/17
8.130.0.0/16
8.130.0.0/15
8.131.0.0/16
8.132.0.0/16
8.132.0.0/15
8.133.0.0/16
8.134.0.0/17
8.134.0.0/16
8.134.128.0/17
8.134.192.0/24
8.135.0.0/17
8.135.0.0/16
8.135.128.0/17
8.136.0.0/17
8.136.0.0/16
8.136.128.0/17
8.140.0.0/15
8.140.0.0/14
8.142.0.0/15
8.144.0.0/15
8.144.0.0/14
8.146.0.0/15
39.96.0.0/14
39.96.0.0/13
39.100.0.0/14
39.104.0.0/15
39.104.0.0/14
39.106.0.0/15
39.108.0.0/17
39.108.0.0/16
39.108.128.0/17
42.96.128.0/17
42.120.0.0/17
42.120.0.0/16
42.120.128.0/17
42.120.248.0/24
42.121.0.0/17
42.121.0.0/16
42.121.128.0/17
42.156.128.0/18
42.156.128.0/17
42.156.192.0/18
43.16.0.0/12
45.113.40.0/23
45.113.40.0/22
45.113.42.0/23
47.92.0.0/15
47.92.0.0/14
47.94.0.0/15
47.96.0.0/15
47.96.0.0/14
47.98.0.0/15
47.100.0.0/15
47.100.0.0/14
47.102.0.0/15
47.104.0.0/16
47.104.0.0/15
47.105.0.0/16
47.106.0.0/16
47.106.0.0/15
47.107.0.0/16
47.108.0.0/16
47.108.0.0/15
47.108.108.0/24
47.109.0.0/16
47.110.0.0/16
47.110.0.0/15
47.111.0.0/16
47.112.0.0/16
47.112.0.0/15
47.113.0.0/16
47.114.0.0/17
47.114.0.0/16
47.114.16.0/24
47.114.128.0/17
47.115.0.0/17
47.115.0.0/16
47.115.128.0/17
47.116.0.0/17
47.116.0.0/16
47.116.128.0/17
47.117.0.0/17
47.117.0.0/16
47.117.128.0/17
47.118.0.0/17
47.118.0.0/16
47.118.128.0/17
47.119.0.0/17
47.119.0.0/16
47.119.128.0/17
47.120.0.0/16
47.120.0.0/15
47.121.0.0/16
47.122.0.0/20
47.122.0.0/19
47.122.16.0/20
59.82.0.0/22
59.82.0.0/21
59.82.4.0/22
59.82.8.0/22
59.82.8.0/21
59.82.12.0/22
59.82.16.0/21
59.82.16.0/20
59.82.24.0/21
59.82.32.0/21
59.82.32.0/20
59.82.40.0/21
59.82.48.0/22
59.82.48.0/21
59.82.52.0/22
59.82.56.0/22
59.82.56.0/21
59.82.60.0/22
59.82.64.0/20
59.82.64.0/19
59.82.80.0/20
59.82.96.0/23
59.82.96.0/22
59.82.98.0/23
59.110.0.0/17
59.110.0.0/16
59.110.128.0/17
60.205.0.0/17
60.205.0.0/16
60.205.128.0/17
60.205.133.0/24
101.37.0.0/17
101.37.0.0/16
101.37.128.0/17
101.132.0.0/16
101.132.0.0/15
101.133.0.0/16
101.133.201.0/24
101.200.0.0/16
101.200.0.0/15
101.201.0.0/16
103.52.196.0/23
103.52.196.0/22
103.52.198.0/23
106.11.0.0/19
106.11.0.0/16
106.11.1.0/24
106.11.32.0/22
106.11.36.0/22
106.11.40.0/21
106.11.48.0/21
106.11.56.0/21
106.11.64.0/19
106.11.128.0/20
106.11.144.0/20
106.11.160.0/20
106.11.176.0/21
106.11.184.0/21
106.11.192.0/23
106.11.194.0/23
106.11.196.0/23
106.11.198.0/24
106.11.199.0/24
106.11.200.0/24
106.11.201.0/24
106.11.202.0/23
106.11.204.0/22
106.11.208.0/21
106.11.216.0/21
106.11.224.0/19
106.14.0.0/16
106.14.0.0/15
106.15.0.0/16
110.75.0.0/17
110.75.0.0/16
110.75.128.0/17
110.75.138.0/23
110.75.227.0/24
110.75.228.0/24
110.75.230.0/24
110.75.233.0/24
110.75.235.0/24
110.75.236.0/22
110.75.240.0/20
110.76.0.0/20
110.76.0.0/19
110.76.2.0/24
110.76.2.0/23
110.76.3.0/24
110.76.8.0/23
110.76.8.0/22
110.76.10.0/23
110.76.12.0/24
110.76.12.0/23
110.76.13.0/24
110.76.15.0/24
110.76.16.0/20
110.76.21.0/24
110.76.23.0/24
110.76.30.0/23
110.76.32.0/20
110.76.48.0/20
110.76.56.0/22
110.76.60.0/22
110.173.192.0/20
110.173.192.0/19
110.173.196.0/24
110.173.208.0/20
112.74.0.0/17
112.74.0.0/16
112.74.128.0/17
112.124.0.0/17
112.124.0.0/16
112.124.128.0/17
112.125.0.0/17
112.125.0.0/16
112.125.128.0/17
112.126.0.0/17
112.126.0.0/16
112.126.128.0/17
112.127.0.0/17
112.127.0.0/16
112.127.128.0/17
114.55.0.0/17
114.55.0.0/16
114.55.128.0/17
114.215.0.0/18
114.215.0.0/16
114.215.64.0/18
114.215.96.0/19
114.215.128.0/19
114.215.160.0/21
114.215.164.0/22
114.215.220.0/22
115.28.0.0/18
115.28.0.0/16
115.28.64.0/18
115.28.128.0/18
115.28.192.0/18
115.29.0.0/17
115.29.0.0/16
115.29.32.0/19
115.29.64.0/18
115.29.128.0/19
115.29.128.0/17
115.124.16.0/22
115.124.16.0/20
115.124.20.0/22
115.124.24.0/21
116.62.0.0/17
116.62.0.0/16
116.62.128.0/17
118.31.0.0/17
118.31.0.0/16
118.31.128.0/17
118.178.0.0/17
118.178.0.0/16
118.178.128.0/17
118.190.0.0/17
118.190.0.0/16
118.190.128.0/17
119.23.0.0/17
119.23.0.0/16
119.23.128.0/17
119.38.208.0/21
119.38.208.0/20
119.38.216.0/21
119.38.219.0/24
119.42.224.0/22
119.42.224.0/19
119.42.228.0/24
119.42.228.0/23
119.42.229.0/24
119.42.230.0/24
119.42.230.0/23
119.42.231.0/24
119.42.232.0/24
119.42.240.0/24
119.42.240.0/23
119.42.241.0/24
119.42.242.0/24
119.42.242.0/23
119.42.243.0/24
120.24.0.0/16
120.24.0.0/15
120.24.0.0/14
120.25.0.0/16
120.26.0.0/16
120.27.0.0/18
120.27.0.0/17
120.27.64.0/18
120.27.79.0/24
120.27.128.0/18
120.27.128.0/17
120.27.192.0/18
120.55.0.0/17
120.55.0.0/16
120.55.128.0/17
120.76.0.0/17
120.76.0.0/16
120.76.0.0/15
120.76.128.0/17
120.77.0.0/17
120.77.0.0/16
120.77.128.0/17
120.77.193.0/24
120.78.0.0/16
120.78.0.0/15
120.79.0.0/16
121.0.16.0/21
121.0.16.0/20
121.0.24.0/22
121.0.28.0/22
121.40.0.0/15
121.40.0.0/14
121.42.0.0/18
121.42.0.0/15
121.42.17.0/24
121.42.64.0/18
121.42.128.0/18
121.42.192.0/19
121.42.224.0/19
121.89.0.0/17
121.89.0.0/16
121.89.128.0/17
121.196.0.0/16
121.196.0.0/14
121.197.0.0/16
121.198.0.0/16
121.199.0.0/16
123.56.0.0/16
123.56.0.0/15
123.57.0.0/24
123.57.0.0/16
123.57.45.0/24
139.129.0.0/24
139.129.0.0/17
139.129.0.0/16
139.129.128.0/17
139.196.0.0/24
139.196.0.0/17
139.196.0.0/16
139.196.128.0/17
139.224.0.0/24
139.224.0.0/17
139.224.0.0/16
139.224.128.0/17
140.205.0.0/24
140.205.0.0/19
140.205.0.0/16
140.205.1.0/24
140.205.32.0/19
140.205.64.0/18
140.205.76.0/24
140.205.122.0/24
140.205.128.0/18
140.205.192.0/18
182.92.0.0/24
182.92.0.0/17
182.92.0.0/16
182.92.128.0/17
203.107.0.0/24
203.107.1.0/24
203.107.6.0/24
203.107.20.0/24
203.107.21.0/24
203.107.22.0/24
203.107.23.0/24
203.107.32.0/24
203.107.32.0/22
203.107.32.0/21
203.107.33.0/24
203.107.34.0/24
203.107.35.0/24
203.107.36.0/24
203.107.36.0/22
203.107.37.0/24
203.107.38.0/24
203.107.39.0/24
203.107.40.0/24
203.107.40.0/23
203.107.40.0/22
203.107.41.0/24
203.107.42.0/24
203.107.42.0/23
203.107.43.0/24
203.107.44.0/24
203.107.44.0/23
203.107.44.0/22
203.107.45.0/24
203.107.46.0/24
203.107.46.0/23
203.107.47.0/24
203.107.48.0/24
203.107.48.0/23
203.107.48.0/22
203.107.49.0/24
203.107.50.0/24
203.107.50.0/23
203.107.51.0/24
203.107.52.0/24
203.107.52.0/23
203.107.52.0/22
203.107.53.0/24
203.107.54.0/24
203.107.54.0/23
203.107.55.0/24
203.107.56.0/24
203.107.56.0/23
203.107.56.0/22
203.107.57.0/24
203.107.58.0/24
203.107.58.0/23
203.107.59.0/24
203.107.60.0/24
203.107.60.0/23
203.107.60.0/22
203.107.61.0/24
203.107.62.0/24
203.107.62.0/23
203.107.63.0/24
203.119.128.0/21
203.119.128.0/20
203.119.144.0/21
203.119.152.0/22
203.119.152.0/21
203.119.156.0/22
203.119.160.0/24
203.119.168.0/22
203.119.168.0/21
203.119.172.0/22
203.119.176.0/21
203.119.176.0/20
203.119.184.0/21
203.119.192.0/19
203.119.192.0/18
203.119.224.0/19
203.209.224.0/20
203.209.224.0/19
203.209.225.0/24
203.209.226.0/23
203.209.228.0/22
203.209.232.0/21
203.209.236.0/23
203.209.240.0/20
203.209.242.0/24
203.209.242.0/23
203.209.243.0/24
203.209.244.0/23
203.209.244.0/22
203.209.246.0/23
203.209.248.0/24
203.209.248.0/23
203.209.249.0/24
203.209.250.0/24
203.209.250.0/23
203.209.251.0/24
203.209.252.0/23
203.209.252.0/22
203.209.254.0/23
218.244.128.0/20
218.244.128.0/19
218.244.144.0/20
223.4.0.0/16
223.4.0.0/14
223.5.0.0/16
223.5.5.0/24
223.6.0.0/16
223.6.6.0/24
223.7.0.0/16

**Comment by alecthw** [comment]
回头有空我看看

**Comment by alecthw** [comment]
已添加阿里云AS37963网段，每次构建自动从ipip.net网页拉取

**Comment by alecthw** [comment]
添加了这里面的国内云计算IP地址
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Cloud/CloudCN
本来是从ipip net上爬的，直到有一天，github actions 服务器地址不能访问ipip.net了，这个方案算是折中吧
